export const productsSample = [
  {
    id: 1,
    name: "Clavier mécanique",
    price: 89,
    category: "Informatique",
    rating: 4.6,
    inStock: true,
  },
  {
    id: 2,
    name: "Souris sans fil",
    price: 45,
    category: "Informatique",
    rating: 4.2,
    inStock: true,
  },
  {
    id: 3,
    name: "Casque audio",
    price: 120,
    category: "Audio",
    rating: 4.8,
    inStock: false,
  },
  {
    id: 4,
    name: "Enceinte Bluetooth",
    price: 75,
    category: "Audio",
    rating: 4.8,
    inStock: true,
  },
  {
    id: 5,
    name: "Tapis de souris",
    price: 15,
    category: "Accessoires",
    rating: 3.9,
    inStock: true,
  },
  {
    id: 6,
    name: "Micro USB",
    price: 60,
    category: "Audio",
    rating: 4.1,
    inStock: true,
  },
];
